

export const AllShoes = [
  {
    id:"1",
    img: "https://m.media-amazon.com/images/I/6125yAfsJKL._AC_UX575_.jpg",
    title: "Nike Air Monarch IV",
    gender:"male",
    prevPrice: "$140,00",
    newPrice: "200",
    company: "Nike",
    color: "white",
    category: "sneakers",
  },
  {
    id:"2",
    img: "https://m.media-amazon.com/images/I/519MRhRKGFL._AC_UX575_.jpg",
    title: "Nike Air Vapormax Plus",
    gender:"male",
    prevPrice: "$140,00",
    newPrice: "200",
    company: "Nike",
    color: "red",
    category: "sneakers",
  },


  {
    id:"3",
    img: "https://m.media-amazon.com/images/I/51+P9uAvb1L._AC_UY695_.jpg",
    title: "Nike Waffle One Sneaker",
    gender:"male",
    prevPrice: "$140,00",
    newPrice: "200",
    company: "Nike",
    color: "green",
    category: "sneakers",
  },
  {
    id:"4",
    img: "https://m.media-amazon.com/images/I/71oEKkghg-L._AC_UX575_.jpg",
    title: "Nike Running Shoe",
    gender:"male",
    prevPrice: "$140,00",
    newPrice: "200",
    company: "Adidas",
    color: "black",
    category: "sneakers",
  },
  {
    id:"5",
    img: "https://m.media-amazon.com/images/I/41M54ztS6IL._AC_SY625._SX._UX._SY._UY_.jpg",
    title: "Flat Slip On Pumps",
    gender:"female",
    prevPrice: "$140,00",
    newPrice: "200",
    company: "Vans",
    color: "green",
    category: "flats",
  },
  {
    id:"6",
    img: "https://m.media-amazon.com/images/I/71zKuNICJAL._AC_UX625_.jpg",
    title: "Knit Ballet Flat",
    gender:"female",
    prevPrice: "$140,00",
    newPrice: "50",
    company: "Adidas",
    color: "black",
    category: "flats",
  },

  {
    id:"7",
    img: "https://m.media-amazon.com/images/I/61V9APfz97L._AC_UY695_.jpg",
    title: "Loafer Flats",
    gender:"female",
    prevPrice: "$140,00",
    newPrice: "50",
    company: "Vans",
    color: "white",
    category: "flats",
  },

  {
    id:"8",
    img: "https://m.media-amazon.com/images/I/71VaQ+V6XnL._AC_UY695_.jpg",
    title: "Nike Zoom Freak",
    gender:"male",
    prevPrice: "$140,00",
    newPrice: "200",
    company: "Nike",
    color: "green",
    category: "sneakers",
  },

  {
    id:"9",
    img: "https://m.media-amazon.com/images/I/61-cBsLhJHL._AC_UY695_.jpg",
    title: "Nike Men's Sneaker",
    gender:"male",
    prevPrice: "$140,00",
    newPrice: "200",
    company: "Adidas",
    color: "blue",
    category: "sneakers",
  },

  {
    id:"10",
    img: "https://m.media-amazon.com/images/I/81xXDjojYKS._AC_UX575_.jpg",
    title: "PUMA BLACK-OCE",
    gender:"male",
    prevPrice: "$140,00",
    newPrice: "150",
    company: "Puma",
    color: "green",
    category: "sneakers",
  },
  {
    id:"11",
    img: "https://m.media-amazon.com/images/I/71E75yRwCDL._AC_UY575_.jpg",
    title: "Pacer Future Sneaker",
    gender:"male",
    prevPrice: "$140,00",
    newPrice: "150",
    company: "Puma",
    color: "red",
    category: "sneakers",
  },
  {
    id:"12",
    img: "https://m.media-amazon.com/images/I/71jeoX0rMBL._AC_UX575_.jpg",
    title: "Unisex-Adult Super",
    gender:"male",
    prevPrice: "$140,00",
    newPrice: "150",
    company: "Puma",
    color: "black",
    category: "sneakers",
  },
  {
    id:"13",
    img: "https://m.media-amazon.com/images/I/61TM6Q9dvxL._AC_UX575_.jpg",
    title: "Roma Basic Sneaker",
    gender:"male",
    prevPrice: "$140,00",
    newPrice: "150",
    company: "Puma",
    color: "white",
    category: "sneakers",
  },
  {
    id:"14",
    img: "https://m.media-amazon.com/images/I/7128-af7joL._AC_UY575_.jpg",
    title: "Pacer Future Doubleknit",
    gender:"male",
    prevPrice: "$140,00",
    newPrice: "150",
    company: "Puma",
    color: "black",
    category: "sneakers",
  },

  {
    id:"15",
    img: "https://m.media-amazon.com/images/I/81xXDjojYKS._AC_UX575_.jpg",
    title: "Fusion Evo Golf Shoe",
    gender:"male",
    prevPrice: "$140,00",
    newPrice: "100",
    company: "Puma",
    color: "green",
    category: "sneakers",
  },
  {
    id:"16",
    img: "https://m.media-amazon.com/images/I/719gdz8lsTS._AC_UX575_.jpg",
    title: "Rainbow Chex Skate",
    gender:"male",
    prevPrice: "$140,00",
    newPrice: "100",
    company: "Vans",
    color: "red",
    category: "flats",
  },
  {
    id:"17",
    img: "https://m.media-amazon.com/images/I/71gpFHJlnoL._AC_UX575_.jpg",
    title: "Low-Top Trainers",
    gender:"male",
    prevPrice: "$140,00",
    newPrice: "100",
    company: "Vans",
    color: "white",
    category: "sandals",
  },
  {
    id:"18",
    img: "https://m.media-amazon.com/images/I/71pf7VFs9CL._AC_UX575_.jpg",
    title: "Vans Unisex Low-Top",
    gender:"male",
    prevPrice: "$140,00",
    newPrice: "100",
    company: "Vans",
    color: "blue",
    category: "sandals",
  },
  {
    id:"19",
    img: "https://m.media-amazon.com/images/I/61N4GyWcHPL._AC_UY575_.jpg",
    title: "Classic Bandana Sneakers",
    gender:"male",
    prevPrice: "$140,00",
    newPrice: "50",
    company: "Nike",
    color: "black",
    category: "sandals",
  },
  {
    id:"20",
    img: "https://m.media-amazon.com/images/I/61bncQ44yML._AC_UX695_.jpg",
    title: "Chunky High Heel",
    gender:"female",
    prevPrice: "$140,00",
    newPrice: "50",
    company: "Vans",
    color: "black",
    category: "heels",
  },
  {
    id:"21",
    img: "https://m.media-amazon.com/images/I/71czu7WgGuL._AC_UY695_.jpg",
    title: "Slip On Stiletto High Heel",
    gender:"female",
    prevPrice: "$140,00",
    newPrice: "100",
    company: "puma",
    color: "black",
    category: "heels",
  },
  {
    id:"22",
    img: "https://m.media-amazon.com/images/I/61men05KRxL._AC_UY625_.jpg",
    title: "DREAM PAIRS Court Shoes",
    gender:"female",
    prevPrice: "$140,00",
    newPrice: "150",
    company: "Nike",
    color: "red",
    category: "heels",
  },

  {
    id:"23",
    img: "https://m.media-amazon.com/images/I/51PGWTXgf-L._AC_UY625_.jpg",
    title: "Low Mid Block Heels",
    gender:"female",
    prevPrice: "$140,00",
    newPrice: "200",
    company: "Nike",
    color: "black",
    category: "heels",
  },
  {
    id:"24",
    img: "https://m.media-amazon.com/images/I/616sA5XUKtL._AC_UY675_.jpg",
    title: "Chunky High Heel",
    gender:"male",
    prevPrice: "$140,00",
    newPrice: "50",
    company: "Adidas",
    color: "black",
    category: "heels",
  },
  {
    id:"25",
    img: "https://m.media-amazon.com/images/I/71h5+MbEK7L._AC_UY625_.jpg",
    title: "Amore Fashion Stilettos",
    gender:"female",
    prevPrice: "$140,00",
    newPrice: "150",
    company: "Adidas",
    color: "white",
    category: "heels",
  },
  {
    id:"26",
    img: "https://m.media-amazon.com/images/I/61uw5RDxKQL._AC_UY625_.jpg",
    title: "Bridal Sandals Glitter",
    gender:"female",
    prevPrice: "$140,00",
    newPrice: "50",
    company: "Adidas",
    color: "black",
    category: "heels",
  },
  {
    id:"27",
    img: "https://m.media-amazon.com/images/I/71yhoZP0l6L._AC_UY695_.jpg",
    title: "Wedding Prom Bridal",
    gender:"female",
    prevPrice: "$140,00",
    newPrice: "50",
    company: "Adidas",
    color: "black",
    category: "flats",
  },
  {
    id: "28",
    img: "https://m.media-amazon.com/images/I/71HnMWVXrAS._SX695_.jpg",
    title: "Reebok Classic Leather Sneaker",
    gender: "male",
    prevPrice: "$120.00",
    newPrice: "180",
    company: "Reebok",
    color: "blue",
    category: "sneakers",
  },
  {
    id: "29",
    img: "https://m.media-amazon.com/images/I/713YubK-Q1L._AC_UL640_FMwebp_QL65_.jpg",
    title: "New Balance 574 Sneaker",
    gender: "male",
    prevPrice: "$130.00",
    newPrice: "190",
    company: "New Balance",
    color: "gray",
    category: "sneakers",
  },
  {
    id: "30",
    img: "https://m.media-amazon.com/images/I/71n+5EQdf+L._AC_UL640_FMwebp_QL65_.jpg",
    title: "Converse Chuck Taylor All Star",
    gender: "male",
    prevPrice: "$100.00",
    newPrice: "150",
    company: "Converse",
    color: "black",
    category: "sneakers",
  },
  {
    id: "31",
    img: "https://m.media-amazon.com/images/I/81sofRDihHL._AC_UL640_FMwebp_QL65_.jpg",
    title: "Reebok Classic Nylon Sneaker",
    gender: "male",
    prevPrice: "$140.00",
    newPrice: "200",
    company: "Reebok",
    color: "white",
    category: "sneakers",
  },
  {
    id: "32",
    img: "https://m.media-amazon.com/images/I/61zT0sOYcSL._AC_UL640_FMwebp_QL65_.jpg",
    title: "New Balance Fresh Foam Roav",
    gender: "male",
    prevPrice: "$150.00",
    newPrice: "220",
    company: "New Balance",
    color: "black",
    category: "sneakers",
  },
  {
    id: "33",
    img: "https://m.media-amazon.com/images/I/71n+5EQdf+L._AC_UL640_FMwebp_QL65_.jpg",
    title: "Converse Chuck 70 High Top",
    gender: "male",
    prevPrice: "$80.00",
    newPrice: "120",
    company: "Converse",
    color: "navy",
    category: "sneakers",
  },
  {
    id: "34",
    img: "https://m.media-amazon.com/images/I/71y6quehMWL._AC_UL640_FMwebp_QL65_.jpg",
    title: "Reebok Classic Leather Ripple",
    gender: "male",
    prevPrice: "$130.00",
    newPrice: "180",
    company: "Reebok",
    color: "black",
    category: "boots",
  },
  {
    id: "35",
    img: "https://m.media-amazon.com/images/I/61Xwu2HTrNL._AC_UL640_FMwebp_QL65_.jpg",
    title: "New Balance 990v5 Running Shoe",
    gender: "male",
    prevPrice: "$180.00",
    newPrice: "250",
    company: "New Balance",
    color: "gray",
    category: "boots",
  },
  {
    id: "36",
    img: "https://m.media-amazon.com/images/I/81-YnzKrryL._AC_UL640_FMwebp_QL65_.jpg",
    title: "Converse Chuck Taylor All Star",
    gender: "male",
    prevPrice: "$150.00",
    newPrice: "210",
    company: "Converse",
    color: "white",
    category: "boots",
  },
  {
    id: "37",
    img: "https://m.media-amazon.com/images/I/81GjnfZ6nJL._AC_UL640_FMwebp_QL65_.jpg",
    title: "Reebok Classic Harman Run",
    gender: "female",
    prevPrice: "$60.00",
    newPrice: "80",
    company: "Reebok",
    color: "pink",
    category: "flats",
  },
  {
    id: "38",
    img: "https://m.media-amazon.com/images/I/714YfoRefJL._AC_UL640_FMwebp_QL65_.jpg",
    title: "New Balance FuelCore NERGIZE",
    gender: "female",
    prevPrice: "$90.00",
    newPrice: "120",
    company: "New Balance",
    color: "leopard print",
    category: "flats",
  },
  {
    id: "39",
    img: "https://m.media-amazon.com/images/I/51PbnHuHt0L._AC_UL640_FMwebp_QL65_.jpg",
    title: "Converse Chuck Taylor Shoreline",
    gender: "female",
    prevPrice: "$120.00",
    newPrice: "170",
    company: "Converse",
    color: "taupe",
    category: "sandals",
  },
  {
    id: "40",
    img: "https://m.media-amazon.com/images/I/717yFwWJzzL._AC_UL640_FMwebp_QL65_.jpg",
    title: "Reebok Princess Sneaker",
    gender: "female",
    prevPrice: "$100.00",
    newPrice: "140",
    company: "Reebok",
    color: "wine",
    category: "heels",
  }
  
];
